server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql:///tfms?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:com/tfms/dao/*Dao.xml